### ISSUE TITLE
Create a wrapper component

### ISSUE THREAD

**Issue by jpetto** [Pocket/curation-tools-frontend#60]
This is a simple component that should provide the wrapper for the main content. The wrapper should be 768px wide and centered on the screen.

Note that this task does _not_ include the header bar visible in the screenshot below.

Please follow the instructions in [OUTREACHY.md](https://github.com/Pocket/curation-tools-frontend/blob/main/OUTREACHY.md) when developing the component.

All tasks should be completed using Typescript.

<img width="1150" alt="wrapper" src="https://user-images.githubusercontent.com/317532/96731680-23f48800-137d-11eb-8f36-2c23752f1d37.png">

**Comment by Adela7** [comment]
Hello @jpetto, I would love to try with this simple component to help me get familiar with Typescript.
Thanks

**Comment by kkyeboah** [comment]
all yours @Adela7

**Comment by Adela7** [comment]
> all yours @Adela7

Thank you, @kkyeboah.

**Comment by Adela7** [comment]
@jpetto and @kkyeboah,

I am considering the following in my implementation:

1. Though not specified in the requirements, is it okay to style the wrapper with light-gray background-color as an added visual aid? It can be removed after review and before merging, but that creates an extra step, so maybe we could stick to no color and using the browser inspection tools. 

2. The project uses Material UI, but this wrapper component does not require any feature-rich UI elements, I am thinking of not duplicating the installation of the base Material UI components, since basic css width and center styling will work fine for this particular component and the detailed look and feel does not get impacted.

Waiting for your green light. 
Thanks

**Comment by kkyeboah** [comment]
@Adela7 thank you for making those considerations, especially since one of them is to help make it easier for @jpetto and me to review your work more easily. 

Both considerations sound reasonable to me, you may process with that implementation but it's not required to add a background color.

**Comment by Adela7** [comment]
@kkyeboah Thank you for the confirmation. I had a couple of setbacks in my implememntation, but this should get me back on track. Thank you.
![error with material ui installation](https://user-images.githubusercontent.com/3534571/97352874-237f5400-188b-11eb-84a9-b6d5d42d930b.PNG)

**Comment by Adela7** [comment]
> @kkyeboah Thank you for the confirmation. I had a couple of setbacks in my implememntation, but this should get me back on track. Thank you.
> ![error with material ui installation](https://user-images.githubusercontent.com/3534571/97352874-237f5400-188b-11eb-84a9-b6d5d42d930b.PNG)

**Update:** I have done a bit of research around the error in the snapshot above and I found that this type of error is because I am working on a Windows operating system and not MacOS. Apparently any Non-Darwin system will generate these errors. 
I learned that it does not pose that much of an issue like I initially thought.

I have been able to successfully start the app and continuing development now. Thank you.

**Comment by Adela7** [comment]
//Wrapper component with 100% height
![Wrapper component with 100% height](https://user-images.githubusercontent.com/3534571/97767961-8a18a200-1b17-11eb-933b-f26a23a0f83f.PNG)

//Visual display of Wrapper component
![Visual display of Wrapper component](https://user-images.githubusercontent.com/3534571/97767958-88e77500-1b17-11eb-9601-978f729d92da.PNG)

//Inspecting Wrapper Component with devtools
![Inspecting Wrapper Component with devtools](https://user-images.githubusercontent.com/3534571/97767957-8553ee00-1b17-11eb-8385-d80db69155cd.PNG)

I tried to implement a couple of tests, but I was not able to get them to pass.
Thanks

**Comment by Adela7** [comment]
@kkyeboah, please kindly have a look to review my PR. 
Patiently waiting and hoping to complete the changes required for a successful merge before 11:45am to finish my application before deadline. :) 
Thanks so much to you and @jpetto.
