### ISSUE TITLE
Additional good first issues!

### ISSUE THREAD

**Issue by jpetto** [Pocket/curation-tools-frontend#69]
If you'd like to work on an issue for your Outreachy application that's not in this repo, the following may be good:

https://github.com/mozilla-frontend-infra/codetribute/issues/248
https://github.com/taskcluster/material-ui-json-schema-viewer/issues/116
https://github.com/taskcluster/material-ui-json-schema-viewer/issues/115

If you'd like to work on any of these issues, comment here and we will coordinate.

**Comment by Joaquin-M2** [comment]
Can I try solving the issue #248 from "codetribute" while you check my last PR?

**Comment by kkyeboah** [comment]
@Joaquin-M2 Great to see how eager you are to solve problems! But let's hold off on starting a second contribution until #71 is reviewed. We want to give every applicant the chance to pick one issue to tackle first.

**Comment by Joaquin-M2** [comment]
Even though I was not assigned to the issue, thanks to my insomnia I have been lurking on the Codetribute code. Are you sure the issue #248 keeps being an issue? It looks solved to me.

I checked this PR, which aims to solve the mentioned issue: https://github.com/mozilla-frontend-infra/codetribute/pull/369

In order to confirm the PR was merged, I just checked the code that pretended to modify that PR: 

- The PR: https://github.com/mozilla-frontend-infra/codetribute/pull/369/files
- The actual code in the Codetribute codebase (check line 62): https://github.com/mozilla-frontend-infra/codetribute/blob/master/src/components/ProjectIntroductionCard/index.jsx

Just for additional confirmation purposes, I doubled checked the issue was fixed by reproducing it in my local machine. I did it in both, Firefox and Chrome browsers, and I didn't get any error in the consoles:

- Firefox console when reproducing the issue: https://i.imgur.com/iYDZeA3.png
- Chrome console when reproducing the issue: https://i.imgur.com/i4j95Zl.png

**Comment by Joaquin-M2** [comment]
@jpetto @kkyeboah Can I fix the Task Cluster issues or you prefer to keep them for newcomers?

**Comment by kkyeboah** [comment]
@Joaquin-M2 If those have not been claimed (by anyone at all, not just the Pocket project applicants), go ahead and comment on the issue and request to work on it.

**Comment by jpetto** [comment]
closing, as the outreachy application process is complete.
